<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="PatronusPulse" failures="2" tests="3" name="TestParallelAll" time="0.334" errors="0" timestamp="2024-09-15T19:20:00 IST">
  <testcase classname="com.pages.BaseClass" name="@BeforeClass setup" time="0.046">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;java.util.Properties.getProperty(String)&amp;quot; because &amp;quot;this.pro&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "java.util.Properties.getProperty(String)" because "this.pro" is null
at com.utilites.ConfigDataClass.getBrowser(ConfigDataClass.java:25)
at com.pages.BaseClass.setup(BaseClass.java:22)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeClass setup -->
  <testcase classname="com.allure.test1" name="testMethod1" time="0.122"/>
  <testcase classname="com.allure.test2" name="testMethod2" time="0.13">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.allure.test2.testMethod2(test2.java:9)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testMethod2 -->
  <testcase classname="com.testcases.LoginTest" name="verify" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.NegativeArraySizeException: -1">
      <![CDATA[java.lang.RuntimeException: java.lang.NegativeArraySizeException: -1
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.lang.NegativeArraySizeException: -1
at com.testcases.LoginTest.loginDataProvider(LoginTest.java:29)
... 15 more
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verify -->
</testsuite> <!-- TestParallelAll -->
